version: 0.2



phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 875525659788.dkr.ecr.us-east-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build --build-arg file_path=./service1/index.html -t service1 .
      - docker tag service1:latest 875525659788.dkr.ecr.us-east-1.amazonaws.com/service1:latest
      - docker build --build-arg file_path=./service2/index.html -t service2 .
      - docker tag service2:latest 875525659788.dkr.ecr.us-east-1.amazonaws.com/service2:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 875525659788.dkr.ecr.us-east-1.amazonaws.com/service1:latest
      - docker push 875525659788.dkr.ecr.us-east-1.amazonaws.com/service2:latest
      - echo Writing image definitions file...
      - printf '[{"name":"act1-container","imageUri":"875525659788.dkr.ecr.us-east-1.amazonaws.com/service1:latest"}]' 875525659788.dkr.ecr.us-east-1.amazonaws.com/service1:latest > imagedefinitions1.json
      - printf '[{"name":"act2-container","imageUri":"875525659788.dkr.ecr.us-east-1.amazonaws.com/service2:latest"}]' 875525659788.dkr.ecr.us-east-1.amazonaws.com/service2:latest > imagedefinitions2.json

artifacts:
    files:
        - imagedefinitions1.json 
        - imagedefinitions2.json 

